### ISSUE TITLE
Palindrome Number

### ISSUE THREAD

**Issue by arungudelli** [arungudelli/go#21]
Given an integer x, return true if x is palindrome integer.

An integer is a palindrome when it reads the same backward as forward.

For example, 121 is a palindrome while 123 is not.

**Constraints:**

-231 <= x <= 231 - 1

**Comment by Chitvan14** [comment]
Hi @arungudelli, can you assign this issue to me, I will be happy to work on this.

**Comment by Ahnaf-codes** [comment]
@arungudelli hey i can do this. assign me

**Comment by arungudelli** [comment]
@Ahnaf-codes Can you work on [https://github.com/arungudelli/go/issues/24]?

**Comment by arungudelli** [comment]
@Chitvan14 Please read contributing guide before proceeding further

**Comment by roshan2152** [comment]
@Chitvan14  Can I work on this?

**Comment by arungudelli** [comment]
@roshan2152 

Sure please read [contributing guide](https://github.com/arungudelli/go/blob/d07db586fa1c01ea0799501af1e8825643fa2037/CONTRIBUTING.md) 

here is the sample article [https://github.com/arungudelli/go/blob/main/content/en/problems/string-anagram-go.md](https://github.com/arungudelli/go/blob/main/content/en/problems/string-anagram-go.md)

If you need help regarding different types of soultions let me know.
