### ISSUE TITLE
Contains Duplicate

### ISSUE THREAD

**Issue by arungudelli** [arungudelli/go#24]
Given an integer array of numbers, return `true` if any number appears **at least twice** in the array, and return `false` if every element is distinct.

**Assumptions:**

- 1 <= nums.length <= 105
- -109 <= nums[i] <= 109

```
Input: nums = [1,2,3,1]
Output: true
```

```
Input: nums = [1,2,3,4]
Output: false
```

**Comment by Ahnaf-codes** [comment]
i can do it @arungudelli

**Comment by arungudelli** [comment]
@Ahnaf-codes 

Read the [contributing guidelines](https://github.com/arungudelli/go/blob/17446946f4af9d665d18f37a9c7230e745a6b448/CONTRIBUTING.md) before proceeding further

**Comment by raginiisingh** [comment]
Hey @arungudelli can you please assign this to me

**Comment by arungudelli** [comment]
@raginiisingh Sure please read [contributing guide](https://github.com/arungudelli/go/blob/d07db586fa1c01ea0799501af1e8825643fa2037/CONTRIBUTING.md) 

here is the sample article [https://github.com/arungudelli/go/blob/main/content/en/problems/string-anagram-go.md](https://github.com/arungudelli/go/blob/main/content/en/problems/string-anagram-go.md)

If you need help regarding different types of soultions let me know.

**Comment by arungudelli** [comment]
@raginiisingh Are you working on this?

**Comment by raginiisingh** [comment]
@arungudelli I am sorry I am a little confused about the language requirement. Is it Go only or I can upload the solution in Java ?

**Comment by arungudelli** [comment]
@raginiisingh You can contribute in Python as well.. Let me know if that works for you
