### ISSUE TITLE
Longest Common Prefix

### ISSUE THREAD

**Issue by arungudelli** [arungudelli/go#25]
Given an array of strings, find the longest common prefix string.

If there is no common prefix, return an empty string "".

**Assumption:**

- 1 <= stringsArray.length <= 200
- 0 <= stringsArray[i].length <= 200
- stringsArray[i] consists of only lowercase English letters.

**Example:**

```
Input: strs = ["flower","flow","flight"]
Output: "fl"
```

**Comment by sambhavgupta0705** [comment]
Yeahh I can work on this one,please assign it to me

**Comment by arungudelli** [comment]
@sambhavgupta0705 


Please Read the [contributing guidelines](https://github.com/arungudelli/go/blob/17446946f4af9d665d18f37a9c7230e745a6b448/CONTRIBUTING.md) before proceeding further

**Comment by sambhavgupta0705** [comment]
ok

**Comment by sambhavgupta0705** [comment]
hello, I will work on it by today

**Comment by arungudelli** [comment]
@sambhavgupta0705 Take your time no hurry..

**Comment by sambhavgupta0705** [comment]
Thanks man!

**Comment by arungudelli** [comment]
@sambhavgupta0705 Please update your forked branch then start working.. It's 3 commits behind

<img width="690" alt="image" src="https://user-images.githubusercontent.com/5583132/193465426-b88e0417-58f2-428f-b743-728544c21ed6.png">

**Comment by sambhavgupta0705** [comment]
Yess I will do it

**Comment by arungudelli** [comment]
@sambhavgupta0705 

please read [contributing guide](https://github.com/arungudelli/go/blob/d07db586fa1c01ea0799501af1e8825643fa2037/CONTRIBUTING.md) 

here is the sample article [https://github.com/arungudelli/go/blob/main/content/en/problems/string-anagram-go.md](https://github.com/arungudelli/go/blob/main/content/en/problems/string-anagram-go.md)

If you need help regarding different types of soultions let me know.

**Comment by sambhavgupta0705** [comment]
hey ,apologies for nit submitting PR till now,will do this by tomorrow as I was busy with some another work so wasn't able to see into it
