### ISSUE TITLE
Valid Parentheses

### ISSUE THREAD

**Issue by arungudelli** [arungudelli/go#26]
Given a string `input` containing just the characters '(', ')', '{', '}', '[' and ']'. 

Check if the `input` string is valid or not.

The string is valid only if 

- Open brackets must be closed by the same type of brackets.
- Open brackets must be closed in the correct order.
- Every close bracket has a corresponding open bracket of the same type.

**Comment by Yukino2002** [comment]
I would like to take this issue up.

**Comment by arungudelli** [comment]
@Yukino2002 Read the [contributing guidelines](https://github.com/arungudelli/go/blob/17446946f4af9d665d18f37a9c7230e745a6b448/CONTRIBUTING.md) before proceeding further

**Comment by Yukino2002** [comment]
Hey, sorry for the error. Could you reassign me the issue?
