### ISSUE TITLE
Roman to Integer

### ISSUE THREAD

**Issue by arungudelli** [arungudelli/go#27]
Given a Roman literals, convert it into an integer

**Assumptions:**

- 1 <= input.length <= 15
- `input` contains only the characters ('I', 'V', 'X', 'L', 'C', 'D', 'M').
- `input` is a valid roman numeral in the range [1, 3999].

Explaine the different ways to solve the problem with time and space complexity (if applicable)

**Comment by aryanlath** [comment]
Hi! Can you assign this issue to me?

**Comment by arungudelli** [comment]
@aryanlath Sure

Read the [contributing guidelines](https://github.com/arungudelli/go/blob/17446946f4af9d665d18f37a9c7230e745a6b448/CONTRIBUTING.md) before proceeding further

**Comment by sambhavgupta0705** [comment]
Hey ,can I also work on this issue?
