### ISSUE TITLE
Two sum problem

### ISSUE THREAD

**Issue by arungudelli** [arungudelli/go#28]
Given an array of integers `numbers` and an integer `sum`, return indexes of the two numbers such the sum of two numbers is equal to `sum`.

**Assumpttion**

- Each input would have exactly one solution, 
- You should not not use the same element twice.
- Return the indexes in any order.

Explain different approaches in Go Language

**Comment by Yukino2002** [comment]
I would like to take this issue up.

**Comment by rakshitgondwal** [comment]
I can work on this.

**Comment by arungudelli** [comment]
@rakshitgondwal Sure 

Read the [contributing guidelines](https://github.com/arungudelli/go/blob/17446946f4af9d665d18f37a9c7230e745a6b448/CONTRIBUTING.md) before proceeding further

**Comment by rakshitgondwal** [comment]
> @rakshitgondwal Sure
> 
> Read the [contributing guidelines](https://github.com/arungudelli/go/blob/17446946f4af9d665d18f37a9c7230e745a6b448/CONTRIBUTING.md) before proceeding further

![Screenshot (329)](https://user-images.githubusercontent.com/98955085/193448867-e3b2dafa-ffa2-4a19-a279-1cccf5216c8a.png)

**Comment by arungudelli** [comment]
@rakshitgondwal let me check give me some time

**Comment by arungudelli** [comment]
@rakshitgondwal delete your node_modules folder and get latest.. The issue should be fixed.. Let me know if you face any issues..

**Comment by sambhavgupta0705** [comment]
Hey can I also work on this issue?

**Comment by arungudelli** [comment]
@sambhavgupta0705 Can you work on [/issues/25] ?

**Comment by sambhavgupta0705** [comment]
Yes I can

**Comment by rakshitgondwal** [comment]
> @rakshitgondwal delete your node_modules folder and get latest.. The issue should be fixed.. Let me know if you face any issues..

I'm still getting the same error

**Comment by arungudelli** [comment]
@rakshitgondwal It should be a problem actually. Even I am using windows. 

Fork the repository again. Instead of old fork.

**Comment by arungudelli** [comment]
@rakshitgondwal Your forked branch is behind of 5 commits update and then take latest in your local

<img width="691" alt="image" src="https://user-images.githubusercontent.com/5583132/193465306-3e90bdc4-9ecc-4568-82c0-12a4eecbc89b.png">
