### ISSUE TITLE
FizzBuzz Golang

### ISSUE THREAD

**Issue by arungudelli** [arungudelli/go#34]
Given an integer n, return a string array answer (1-indexed) where:

answer[i] == "FizzBuzz" if i is divisible by 3 and 5.
answer[i] == "Fizz" if i is divisible by 3.
answer[i] == "Buzz" if i is divisible by 5.
answer[i] == i (as a string) if none of the above conditions are true.

**Comment by aditya-agr** [comment]
I can solve this problem.

**Comment by arungudelli** [comment]
@aditya-agr  Read the contributing guidelines 

https://github.com/arungudelli/go/blob/94e8904b6cb0b64b9c550a065b0af7583d80649d/CONTRIBUTING.md

And let me know if you can explain the soultion in simple english.

**Comment by aditya-agr** [comment]
yes I can explain the solution in simple english.

**Comment by arungudelli** [comment]
@aditya-agr Fork the repository.. And start working.. If everything is fine then I can merge.. For more details Please read the contributing guidelines .. And let me know if you have any queries

**Comment by aditya-agr** [comment]
please review my pull request.
