### ISSUE TITLE
Unique Number of Occurrences Golang

### ISSUE THREAD

**Issue by arungudelli** [arungudelli/go#35]
Given an array of integers arr, return true if the number of occurrences of each value in the array is unique, or false otherwise.

https://leetcode.com/problems/unique-number-of-occurrences/

**Comment by JatinSingh08** [comment]
Hey @arungudelli , Assign this to me...I've good knowledge of dsa & i've done this question as well

**Comment by arungudelli** [comment]
@JatinSingh08 Please read the contributing guidelines 

https://github.com/arungudelli/go/blob/94e8904b6cb0b64b9c550a065b0af7583d80649d/CONTRIBUTING.md

Let me know if you can explain the soultion in simple english. 

https://golangtutorial.dev/problems/string-anagram-go/

**Comment by Anandbrewery** [comment]
hey i am interested
