### ISSUE TITLE
Merge Two Sorted Lists Golang

### ISSUE THREAD

**Issue by arungudelli** [arungudelli/go#36]
You are given the heads of two sorted linked lists list1 and list2.

Merge the two lists in a one sorted list. The list should be made by splicing together the nodes of the first two lists.

Return the head of the merged linked list.

https://leetcode.com/problems/merge-two-sorted-lists/

**Comment by bhoomitri4** [comment]
Hey can I work on this issue!! I am really excited to do so. Please assign it to me!!

**Comment by arungudelli** [comment]
@bhoomitri4 In which language u want to write python or Golang?

**Comment by bhoomitri4** [comment]
I would like to do this in python.

**Comment by arungudelli** [comment]
@bhoomitri4 please comment on the issue https://github.com/arungudelli/python.shiksha/issues/50

**Comment by botketan** [comment]
Can i do this in c++?

**Comment by Naveen-Nair** [comment]
@arungudelli Hey! Can i work on this issue?
